#!/usr/bin/env bash
IFS=$'\n\t';
set -euo pipefail;


tag="${1:-}";

if [ -z "$tag" ]
then
	edition=${PWD##*/};
	tag=$(git log --format='%D' | sed -n "/^tag: $edition-/I {s/.* //; p;q;}" || true);
fi;


git log --format='%s' "$tag"..HEAD |
awk -v ver="$tag" '
BEGIN {
	pfx = tolower(ver);
	sub(/-.*/,"",pfx);
	sub(/.*-v/,"",ver);

	ptn = pfx;
	if (ptn ~ /azure/) {ptn = ptn "|dev";}
	if (ptn ~ /dev/  ) {ptn = ptn "|base";}
	ptn = "(" ptn ")\\.";
}
{$0 = tolower($0);}
$0 ~ ptn "1" {bump[1]++;}
$0 ~ ptn "2" {bump[2]++;}
$0 ~ ptn "3" {bump[3]++;}
END {
	if (maj == 0 && min == 0 && pat == 0) {pat++;}
	split(ver,sem,".");
	for (i = 3; i >= 1; i--)
	{
		if (bump[i] > 0)
		{
			sem[i]++;
			for (j = i+1; j <= 3; j++)
			{
				sem[j] = 0;
			}
		}
	}

	printf("%s-v%d.%d.%d",pfx,sem[1],sem[2],sem[3]);
}'
